/* Generated by scripts/fetch-glibc.sh — equivalent of glibc's build-time
   gnu/stubs.h for arch-linux-gnu (stub functions on this configuration).  */
#ifndef _GNU_LIBC_STUBS_H
#define _GNU_LIBC_STUBS_H

#define __stub_chflags
#define __stub_fchflags
#define __stub_gtty
#define __stub_revoke
#define __stub_setlogin
#define __stub_sigreturn
#define __stub_stty

#endif /* _GNU_LIBC_STUBS_H */
