#!/usr/bin/env python3
"""glibc-abi-gen.py — generate bake's glibc ABI table from upstream abilists.

Runs on the HOST (pure text processing, no readelf, no builds, no Docker).
Invoked by scripts/fetch-glibc.sh.

Source of truth: the per-architecture `.abilist` files shipped in the glibc
release tarball (sysdeps/unix/sysv/linux/<arch>[/64]/lib<name>.abilist).
Upstream maintains these to validate every build; each line records the
symbol, the version node at which it was introduced, its kind (F/D), and —
for data — its exact size. One recent tarball therefore seeds every target
glibc version from the baseline up to the seed version.

Output format (lib/libc/glibc/abilists, bake-owned, plain text):

    format 1
    seed glibc <version>
    lib <name> sover <n> [removed-in <maj.min>]     # fixed stub-lib set
    target <triple>
    [target <triple>]
    fn  <name> <lib> <ver>[,<ver>...]               # sorted by name
    obj <name> <lib> <size> <ver>[,<ver>...]

Version lists are deduplicated, sorted ascending. The default (@@) version
is NOT recorded: the stub generator picks the greatest version <= the
target glibc version, matching what real linkers resolve.
"""

import argparse
import sys
from pathlib import Path

# The eight stub libraries. `removed-in` marks libraries merged into
# libc.so.6 at glibc 2.34 (not linked for targets >= that version).
LIBS = [
    ("m", 6, None),
    ("c", 6, None),
    ("ld", 2, None),
    ("resolv", 2, None),
    ("pthread", 0, "2.34"),
    ("dl", 2, "2.34"),
    ("rt", 1, "2.34"),
    ("util", 1, "2.34"),
]

# abilist location per triple, relative to the extracted tarball root.
TRIPLE_DIRS = {
    "x86_64-linux-gnu": "sysdeps/unix/sysv/linux/x86_64/64",
    "aarch64-linux-gnu": "sysdeps/unix/sysv/linux/aarch64",
}


def ver_key(ver):
    return tuple(int(p) for p in ver[len("GLIBC_"):].split("."))


def parse_abilist(path):
    """abilist → {symbol: {"kind", "size", "versions"}}.

    Line format: <GLIBC_x.y[.z]> <symbol> F | <GLIBC_x.y[.z]> <symbol> D <0xSIZE>
    """
    syms = {}
    for line in Path(path).read_text().splitlines():
        f = line.split()
        if len(f) == 3 and f[2] == "F":
            ver, name, kind = f[0], f[1], "fn"
            size = 0
        elif len(f) == 4 and f[2] == "D":
            ver, name, kind = f[0], f[1], "obj"
            size = int(f[3], 0)
        else:
            continue
        if not ver.startswith("GLIBC_"):
            continue
        e = syms.setdefault(
            name, {"kind": kind, "size": size, "versions": []})
        e["versions"].append(ver)
        if kind == "obj" and size > e["size"]:
            e["size"] = size
    return syms


def collect(src_root, triple):
    table = {}
    base = Path(src_root) / TRIPLE_DIRS[triple]
    for lib, _sover, _removed in LIBS:
        fname = "ld.abilist" if lib == "ld" else f"lib{lib}.abilist"
        path = base / fname
        if not path.is_file():
            # e.g. libutil has no separate abilist on some arches (its
            # symbols live in libc there). The compat shell just carries
            # nothing to link.
            print(f"warning: {triple}: {fname} missing; "
                  f"lib {lib} gets no symbols", file=sys.stderr)
            continue
        n = 0
        for name, e in parse_abilist(path).items():
            e["lib"] = lib
            if name not in table:
                table[name] = e
                n += 1
        print(f"  {triple} lib {lib}: {n} symbols", file=sys.stderr)
    return table


def emit(tables, seed_version, out):
    lines = [
        "# bake glibc ABI table — generated by scripts/glibc-abi-gen.py; do not edit",
        "format 1",
        f"seed glibc {seed_version}",
    ]
    for lib, sover, removed in LIBS:
        line = f"lib {lib} sover {sover}"
        if removed:
            line += f" removed-in {removed}"
        lines.append(line)
    for triple in tables:
        lines.append(f"target {triple}")
    for triple, table in tables.items():
        lines.append("")
        lines.append(f"[target {triple}]")
        for name in sorted(table):
            e = table[name]
            # Emit bare x.y[.z] — the bake-side parser expects no prefix.
            vers = ",".join(
                v[len("GLIBC_"):] for v in sorted(set(e["versions"]),
                                                  key=ver_key))
            if e["kind"] == "fn":
                lines.append(f"fn {name} {e['lib']} {vers}")
            else:
                lines.append(f"obj {name} {e['lib']} {e['size']} {vers}")
    Path(out).write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed-version", required=True,
                    help="glibc version of the extracted tarball")
    ap.add_argument("--src", required=True,
                    help="extracted glibc tarball root")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    tables = {}
    for triple in TRIPLE_DIRS:
        tables[triple] = collect(args.src, triple)
        print(f"  {triple}: {len(tables[triple])} symbols total",
              file=sys.stderr)

    emit(tables, args.seed_version, args.out)
    print(f"wrote {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
